import type { Option, SupportCard } from './types.ts';

/** Data trainee (horse) yang bisa dipilih user. */
export const traineeOptions: Option<number>[] = [
	{ name: 'Admire Groove', value: 100000, status: 'unreleased' },
	{ name: 'Admire Vega (Glacialis Vega)', value: 103302, status: 'upcoming' },
	{ name: 'Admire Vega (Starry Nocturne)', value: 103301, status: 'upcoming' },
	{ name: 'Agnes Digital (Agnes♡Jiangshi)', value: 101902, status: 'upcoming' },
	{ name: 'Agnes Digital (Super Express! Full Color Special)', value: 101901, status: 'upcoming' },
	{ name: 'Agnes Tachyon (Lunatic Lab)', value: 103202, status: 'upcoming' },
	{ name: 'Agnes Tachyon (tach-nology)', value: 103201, status: 'released' },
	{ name: 'Agnes Tachyon (Σ Experiment)', value: 103203, status: 'upcoming' },
	{ name: 'Air Groove (Empress Road)', value: 101801, status: 'released' },
	{ name: 'Air Groove (Quercus Civilis)', value: 101802, status: 'released' },
	{ name: 'Air Messiah (Inherited Hope)', value: 111101, status: 'upcoming' },
	{ name: 'Air Shakur ([unsigned])', value: 103601, status: 'upcoming' },
	{ name: "Air Shakur (Belphegor's Prime)", value: 103602, status: 'upcoming' },
	{ name: 'Almond Eye', value: 100000, status: 'unreleased' },
	{ name: 'Aston Machan (Everlasting Sweet Treat)', value: 108702, status: 'upcoming' },
	{ name: 'Aston Machan (Flare)', value: 108701, status: 'upcoming' },
	{ name: 'Bamboo Memory (Ambition of the Black Iron)', value: 105301, status: 'upcoming' },
	{ name: 'Bamboo Memory (Ultra☆Marine)', value: 105302, status: 'upcoming' },
	{ name: 'Believe (精粋)', value: 109501, status: 'upcoming' },
	{ name: 'Biko Pegasus (Gale Pegasus Type Zero)', value: 105401, status: 'upcoming' },
	{ name: 'Biwa Hayahide (Engineered Victory)', value: 102303, status: 'upcoming' },
	{ name: 'Biwa Hayahide (Noel Rouge Carol)', value: 102302, status: 'upcoming' },
	{ name: 'Biwa Hayahide (pf. Winning Equation...)', value: 102301, status: 'released' },
	{ name: 'Blast Onepiece', value: 100000, status: 'unreleased' },
	{ name: 'Bubble Gum Fellow (POPPING!)', value: 112401, status: 'upcoming' },
	{ name: 'Buena Vista', value: 100000, status: 'unreleased' },
	{ name: 'Calstone Light O (One True Path)', value: 112001, status: 'upcoming' },
	{ name: 'Cesario (Future Weaver)', value: 111001, status: 'upcoming' },
	{ name: 'Cesario (Twinbell Queen)', value: 111002, status: 'upcoming' },
	{ name: 'Cheval Grand ([夏凪ネイビードロップ])', value: 108902, status: 'upcoming' },
	{ name: 'Cheval Grand (Grand Itinéraire)', value: 108901, status: 'upcoming' },
	{ name: 'Chrono Genesis (Prismatic Curator)', value: 113301, status: 'upcoming' },
	{ name: 'Copano Rickey (Dazzling ☆ Lucky Wear)', value: 109802, status: 'upcoming' },
	{ name: 'Copano Rickey (Yin-yang Bagua ☆ Lucky Costume)', value: 109801, status: 'upcoming' },
	{ name: "Curren Bouquetd'or", value: 100000, status: 'unreleased' },
	{ name: 'Curren Chan (Fille Éclair)', value: 103801, status: 'released' },
	{ name: 'Curren Chan (Ma Chérie)', value: 103802, status: 'upcoming' },
	{ name: 'Daiichi Ruby (Brilliant Red Gemstone)', value: 108501, status: 'upcoming' },
	{ name: 'Daiichi Ruby (Flowing Blue)', value: 108502, status: 'upcoming' },
	{ name: 'Daitaku Helios (Fun ☆ Fun ☆ Party Night)', value: 106501, status: 'upcoming' },
	{ name: 'Daitaku Helios (Joyful Jamboree!)', value: 106502, status: 'upcoming' },
	{ name: 'Daiwa Scarlet (Scarlet Nuit Étoilée)', value: 100902, status: 'upcoming' },
	{ name: 'Daiwa Scarlet (Peak Blue)', value: 100901, status: 'released' },
	{ name: 'Dantsu Flame', value: 100000, status: 'unreleased' },
	{ name: 'Daring Heart', value: 100000, status: 'unreleased' },
	{ name: 'Daring Tact', value: 100000, status: 'unreleased' },
	{ name: 'Dream Journey (Dreamland Memento)', value: 111901, status: 'upcoming' },
	{ name: 'Duramente (Red in Black)', value: 110801, status: 'upcoming' },
	{ name: 'Durandal (Chevalier Fidèle)', value: 112101, status: 'upcoming' },
	{ name: 'Eishin Flash (Collect・Chocolatier)', value: 103702, status: 'upcoming' },
	{ name: 'Eishin Flash (Meisterschaft)', value: 103701, status: 'upcoming' },
	{ name: 'Eishin Flash (Reines Plätschern)', value: 103703, status: 'upcoming' },
	{ name: 'El Condor Pasa (El☆Número 1)', value: 101401, status: 'released' },
	{ name: 'El Condor Pasa (Kukulkan Warrior)', value: 101402, status: 'released' },
	{ name: 'Espoir City (Red Devil Gear)', value: 108101, status: 'upcoming' },
	{ name: 'Fenomeno (Black Flame of Righteousness)', value: 112701, status: 'upcoming' },
	{ name: 'Fine Motion (Noble Seamair)', value: 102201, status: 'upcoming' },
	{ name: 'Fine Motion (Titania)', value: 102202, status: 'upcoming' },
	{ name: 'Fuji Kiseki (Shooting Star Revue)', value: 100501, status: 'upcoming' },
	{ name: 'Fuji Kiseki (Succès Étoile)', value: 100502, status: 'upcoming' },
	{ name: 'Furioso (Triumphant Return of the Auspicious Star)', value: 107901, status: 'upcoming' },
	{ name: 'Fusaichi Pandora (Assorted Cuteness♡)', value: 111301, status: 'upcoming' },
	{ name: 'Gentildonna (Regina dei Fiori)', value: 111601, status: 'upcoming' },
	{ name: 'Gold City (Akizakura Danzatrice)', value: 104002, status: 'upcoming' },
	{ name: 'Gold City (Authentic 1928)', value: 104001, status: 'upcoming' },
	{ name: 'Gold City (Boho Flare)', value: 104003, status: 'upcoming' },
	{ name: 'Gold Ship (La Mode 564)', value: 100703, status: 'upcoming' },
	{ name: 'Gold Ship (Red Strife)', value: 100701, status: 'released' },
	{ name: 'Gold Ship (Run! Fun! Watergun!)', value: 100702, status: 'upcoming' },
	{ name: 'Gran Alegria (sMile My Way!)', value: 113101, status: 'upcoming' },
	{ name: 'Grass Wonder (Honor of the Azure Flame)', value: 101103, status: 'upcoming' },
	{ name: 'Grass Wonder (Stone-Piercing Blue)', value: 101101, status: 'released' },
	{ name: 'Grass Wonder (Saintly Jade Cleric)', value: 101102, status: 'released' },
	{ name: 'Haru Urara (First Urara ♪ Saku Sakura)', value: 105202, status: 'upcoming' },
	{ name: 'Haru Urara (Bestest Prize ♪)', value: 105201, status: 'released' },
	{ name: 'Hishi Akebono (Bono ☆ Alla Moda)', value: 102801, status: 'upcoming' },
	{ name: 'Hishi Akebono Magic Night Garland)', value: 102802, status: 'upcoming' },
	{ name: 'Hishi Amazon (Azure Amazon)', value: 101201, status: 'released' },
	{ name: 'Hishi Amazon (Hungry Veil)', value: 101202, status: 'upcoming' },
	{ name: 'Hishi Miracle ([ハッピー・リトル・ノーツ])', value: 110602, status: 'upcoming' },
	{ name: 'Hishi Miracle (Miracle Make-up!)', value: 110601, status: 'upcoming' },
	{ name: 'Hokko Tarumae (Pastel Marine Locodol)', value: 109902, status: 'upcoming' },
	{ name: 'Hokko Tarumae (Star・Light・Ship)', value: 109901, status: 'upcoming' },
	{ name: 'Ikuno Dictus (Mantle of Steel)', value: 106301, status: 'upcoming' },
	{ name: 'Inari One (Fields of Gold)', value: 103402, status: 'upcoming' },
	{ name: 'Inari One (Inari Yukari Edomurasaki)', value: 103401, status: 'upcoming' },
	{ name: 'Ines Fujin (All-time Fever)', value: 103101, status: 'upcoming' },
	{ name: 'Ines Fujin (Hello Hello Island)', value: 103103, status: 'upcoming' },
	{ name: 'Ines Fujin (MELTY GIFT)', value: 103102, status: 'upcoming' },
	{ name: "Jungle Pocket (Ruler's Battle Cry)", value: 109401, status: 'upcoming' },
	{ name: 'K.S. Miracle ([秋日色アンダンテ])', value: 109302, status: 'upcoming' },
	{ name: 'K.S. Miracle (Prism)', value: 109301, status: 'upcoming' },
	{ name: 'Katsuragi Ace (Dragon Rising to the Top)', value: 110401, status: 'upcoming' },
	{ name: 'Katsuragi Ace (Pen Name: Ink Dragon)', value: 110402, status: 'upcoming' },
	{ name: 'Kawakami Princess (Princess of Pink)', value: 103901, status: 'upcoming' },
	{ name: 'Kawakami Princess (Suikan Beauty)', value: 103902, status: 'upcoming' },
	{ name: 'King Halo (Evergreen Identity)', value: 106103, status: 'upcoming' },
	{ name: 'King Halo (King of Emeralds)', value: 106101, status: 'released' },
	{ name: 'King Halo (Noble White Cheer Attire)', value: 106102, status: 'upcoming' },
	{ name: 'Kitasan Black (Crowning Ooban)', value: 106801, status: 'upcoming' },
	{ name: 'Kitasan Black (Final Bloom)', value: 106803, status: 'upcoming' },
	{ name: 'Kitasan Black (Jubilant Star・Auspicious Crane)', value: 106802, status: 'upcoming' },
	{ name: 'Loves Only You (9927 Wishes)', value: 113201, status: 'upcoming' },
	{ name: 'Lucky Lilac', value: 100000, status: 'unreleased' },
	{ name: 'Manhattan Cafe (Creeping Black)', value: 102501, status: 'upcoming' },
	{ name: 'Manhattan Cafe (Willow-Green Evening)', value: 102502, status: 'upcoming' },
	{ name: 'Maruzensky (Auspicious Maiden of Divine Speed)', value: 100403, status: 'upcoming' },
	{ name: 'Maruzensky (Blasting Off ☆ Summer Night)', value: 100402, status: 'upcoming' },
	{ name: 'Maruzensky (Formula R)', value: 100401, status: 'released' },
	{ name: 'Marvelous Sunday (☆Sparkling★Dazzling☆Exciting∞Marvelous∞)', value: 105501, status: 'upcoming' },
	{ name: 'Marvelous Sunday (Trick ☆ Ribonetta)', value: 105502, status: 'upcoming' },
	{ name: 'Matikanefukukitaru (Good Omen・First Storm)', value: 105602, status: 'upcoming' },
	{ name: 'Matikanefukukitaru (Rising☆Fortune)', value: 105601, status: 'released' },
	{ name: 'Matikanetannhauser (Blue Turbulence)', value: 106202, status: 'upcoming' },
	{ name: 'Matikanetannhauser (Pan~Paka~Tiru~Toto)', value: 106201, status: 'upcoming' },
	{ name: 'Mayano Top Gun (Rocking☆MewMeow)', value: 102403, status: 'upcoming' },
	{ name: 'Mayano Top Gun (Scramble☆Zone)', value: 102401, status: 'released' },
	{ name: 'Mayano Top Gun (Sunlight Bouquet)', value: 102402, status: 'released' },
	{ name: 'Meisho Doto (Blue/Raging)', value: 105801, status: 'upcoming' },
	{ name: "Meisho Doto (Dot-o'-Lantern)", value: 105802, status: 'upcoming' },
	{ name: 'Mejiro Ardan (Clinochlore Line)', value: 107101, status: 'upcoming' },
	{ name: 'Mejiro Ardan (Neige Émeraude)', value: 107102, status: 'upcoming' },
	{ name: 'Mejiro Bright (Brunissage Line)', value: 107401, status: 'upcoming' },
	{ name: 'Mejiro Bright (Starry Snow Lolita)', value: 107402, status: 'upcoming' },
	{ name: 'Mejiro Dober (Twisted Line)', value: 105901, status: 'upcoming' },
	{ name: 'Mejiro Dober (Vacances Saphir)', value: 105902, status: 'upcoming' },
	{ name: 'Mejiro Mcqueen (Frontline Elegance)', value: 101301, status: 'released' },
	{ name: 'Mejiro Mcqueen (End of the Skies)', value: 101302, status: 'released' },
	{ name: 'Mejiro Mcqueen (Fair Lady of the Waves)', value: 101303, status: 'upcoming' },
	{ name: 'Mejiro Palmer (Line Breakthrough)', value: 106401, status: 'upcoming' },
	{ name: 'Mejiro Palmer (Warm-Hearted Reindeer)', value: 106402, status: 'upcoming' },
	{ name: 'Mejiro Ramonu (Onyx Line)', value: 108601, status: 'upcoming' },
	{ name: 'Mejiro Ramonu (Untouchable Eden)', value: 108602, status: 'upcoming' },
	{ name: 'Mejiro Ryan (Marguerite・Latte)', value: 102702, status: 'upcoming' },
	{ name: 'Mejiro Ryan (Down the Line)', value: 102701, status: 'released' },
	{ name: 'Mihono Bourbon (Code Glaçage)', value: 102602, status: 'upcoming' },
	{ name: 'Mihono Bourbon (MB-19890425)', value: 102601, status: 'released' },
	{ name: 'Mr. C.B. (Clear Bliss)', value: 105701, status: 'upcoming' },
	{ name: 'Mr. C.B. (Dazzling Kabuki Flower)', value: 105702, status: 'upcoming' },
	{ name: 'Nakayama Festa (Dramatic Turnabout)', value: 104901, status: 'upcoming' },
	{ name: 'Narita Brian (Hungry Wolf)', value: 101602, status: 'upcoming' },
	{ name: 'Narita Brian (Maverick)', value: 101601, status: 'released' },
	{ name: 'Narita Taishin (Difference Engineer)', value: 105002, status: 'upcoming' },
	{ name: 'Narita Taishin (Nevertheless)', value: 105001, status: 'released' },
	{ name: 'Narita Taishin (Stray Light Override)', value: 105003, status: 'upcoming' },
	{ name: 'Narita Top Road (Celestial Road)', value: 107702, status: 'upcoming' },
	{ name: 'Narita Top Road (The Proud Road)', value: 107701, status: 'upcoming' },
	{ name: 'Neo Universe (Like “ZEER”)', value: 110502, status: 'upcoming' },
	{ name: 'Neo Universe (Universe-Naut)', value: 110501, status: 'upcoming' },
	{ name: 'Nice Nature (Converging Wishes)', value: 106003, status: 'upcoming' },
	{ name: 'Nice Nature (Poinsettia Ribbon)', value: 106001, status: 'released' },
	{ name: 'Nice Nature (RUN＆WIN)', value: 106002, status: 'upcoming' },
	{ name: 'Nishino Flower (Sweet Juneberry)', value: 105102, status: 'upcoming' },
	{ name: 'Nishino Flower (Tiered Petal)', value: 105101, status: 'upcoming' },
	{ name: 'No Reason (Swift Crimson Armor)', value: 109601, status: 'upcoming' },
	{ name: 'North Flight (Looking Fly!)', value: 108201, status: 'upcoming' },
	{ name: 'Oguri Cap (Miraculous White Star)', value: 100602, status: 'upcoming' },
	{ name: 'Oguri Cap (Starlight Beat)', value: 100601, status: 'released' },
	{ name: 'Orfevre (Total Dominion)', value: 111501, status: 'upcoming' },
	{ name: 'Rhein Kraft (Dream Successor)', value: 110901, status: 'upcoming' },
	{ name: 'Rhein Kraft (Eternal Fairytale)', value: 110902, status: 'upcoming' },
	{ name: 'Rice Shower (Make up Vampire!)', value: 103002, status: 'upcoming' },
	{ name: 'Rice Shower (Rosy Dreams)', value: 103001, status: 'released' },
	{ name: 'Rice Shower (Yummy Dreamy Fairy)', value: 103003, status: 'upcoming' },
	{ name: 'Royce and Royce', value: 100000, status: 'unreleased' },
	{ name: 'Sakura Bakushin O (Red-Hot Leader)', value: 104102, status: 'upcoming' },
	{ name: 'Sakura Bakushin O (Blossom in Learning)', value: 104101, status: 'released' },
	{ name: 'Sakura Chitose O', value: 100000, status: 'unreleased' },
	{ name: 'Sakura Chiyono O (Fleur Enneigée)', value: 106902, status: 'upcoming' },
	{ name: 'Sakura Chiyono O (Hinoshita Kaisan・Hana Akari)', value: 106901, status: 'upcoming' },
	{ name: 'Sakura Laurel (Saisir le Rêve)', value: 107601, status: 'upcoming' },
	{ name: 'Samson Big', value: 100000, status: 'unreleased' },
	{ name: 'Satono Crown ([晴島花麗])', value: 108802, status: 'upcoming' },
	{ name: 'Satono Crown (Emerald Journey)', value: 108801, status: 'upcoming' },
	{ name: 'Satono Diamond (Chevalier Bleu)', value: 106703, status: 'upcoming' },
	{ name: 'Satono Diamond (Floral Star・Prosperous Green)', value: 106702, status: 'upcoming' },
	{ name: 'Satono Diamond (Natural Brilliance)', value: 106701, status: 'upcoming' },
	{ name: 'Seeking The Pearl (Be♪Witched)', value: 104202, status: 'upcoming' },
	{ name: 'Seeking The Pearl (Rocket ☆ Star)', value: 104201, status: 'upcoming' },
	{ name: 'Seiun Sky (Reeling in the Big One)', value: 102001, status: 'released' },
	{ name: 'Seiun Sky (Soirée de Chaton)', value: 102002, status: 'upcoming' },
	{ name: 'Shinko Windy (Wicked Punk)', value: 104301, status: 'upcoming' },
	{ name: 'Silence Suzuka (Emerald Among the Waves)', value: 100202, status: 'upcoming' },
	{ name: 'Silence Suzuka (Innocent Silent)', value: 100201, status: 'released' },
	{ name: 'Sirius Symboli (Féroce)', value: 107001, status: 'upcoming' },
	{ name: 'Sirius Symboli (Louve Stellaire)', value: 107002, status: 'upcoming' },
	{ name: 'Smart Falcon (LOVE☆4EVER)', value: 104601, status: 'released' },
	{ name: 'Smart Falcon (Luminous ☆ Twirler)', value: 104603, status: 'upcoming' },
	{ name: 'Smart Falcon (Twilight Triumph)', value: 104602, status: 'upcoming' },
	{ name: 'Sounds Of Earth (Ritmo Della Terra)', value: 110201, status: 'upcoming' },
	{ name: 'Special Week (Hopping ♪ Vitamin Heart)', value: 100102, status: 'upcoming' },
	{ name: 'Special Week (Special Dreamer)', value: 100101, status: 'released' },
	{ name: 'Special Week (Supreme Commander of the Rising Sun)', value: 100103, status: 'upcoming' },
	{ name: 'Still In Love (Scarlet Vow Raiment)', value: 109701, status: 'upcoming' },
	{ name: 'Super Creek (Chiffon Ribbon Mummy)', value: 104502, status: 'upcoming' },
	{ name: 'Super Creek (Flowery Shadow Amongst the Gentle Rain)', value: 104503, status: 'upcoming' },
	{ name: 'Super Creek (Murmuring Stream)', value: 104501, status: 'released' },
	{ name: 'Sweep Tosho (Platanus Witch)', value: 104401, status: 'upcoming' },
	{ name: 'Sweep Tosho (Realize・Rune)', value: 104402, status: 'upcoming' },
	{ name: 'Symboli Kris S (Jetblack Automaton)', value: 108302, status: 'upcoming' },
	{ name: 'Symboli Kris S (Onyx Soldier)', value: 108301, status: 'upcoming' },
	{ name: 'Symboli Rudolf (Archer of the White Moon)', value: 101702, status: 'upcoming' },
	{ name: "Symboli Rudolf (Emperor's Path)", value: 101701, status: 'released' },
	{ name: 'T.M. Opera O (Blue Dazzle)', value: 101502, status: 'upcoming' },
	{ name: 'T.M. Opera O (O Sole Suo!)', value: 101501, status: 'released' },
	{ name: 'Taiki Shuttle (Bubblegum ☆ Memories)', value: 101002, status: 'upcoming' },
	{ name: 'Taiki Shuttle (Wild Frontier)', value: 101001, status: 'released' },
	{ name: 'Tamamo Cross (Ferocious Thunder)', value: 102102, status: 'upcoming' },
	{ name: 'Tamamo Cross (With Lightning Speed)', value: 102101, status: 'upcoming' },
	{ name: 'Tanino Gimlet (Embodiment of Keravnos)', value: 108401, status: 'upcoming' },
	{ name: 'Tanino Gimlet (With a Twist)', value: 108402, status: 'upcoming' },
	{ name: 'Tap Dance City (GLITTER!)', value: 110701, status: 'upcoming' },
	{ name: 'Tap Dance City (Tap! Tap! Tap!)', value: 110702, status: 'upcoming' },
	{ name: 'Tokai Teio (Beyond the Horizon)', value: 100302, status: 'released' },
	{ name: 'Tokai Teio (Dream Butterfly of Purple Clouds)', value: 100303, status: 'upcoming' },
	{ name: 'Tokai Teio (Peak Joy)', value: 100301, status: 'released' },
	{ name: 'Tosen Jordan (Aurore☆Vacances)', value: 104802, status: 'upcoming' },
	{ name: 'Tosen Jordan (Pop ☆ Joker)', value: 104801, status: 'upcoming' },
	{ name: 'Transcend (ZOKU-ZOKU GIZMO)', value: 108001, status: 'upcoming' },
	{ name: 'Tsurumaru Tsuyoshi (Dream Bold, Stand Tall, Tsuyoshi!)', value: 107301, status: 'upcoming' },
	{ name: 'Twin Turbo (Blast Mode! Turbo Engine)', value: 106601, status: 'upcoming' },
	{ name: 'Verxina (Le Beau Sommet)', value: 109001, status: 'upcoming' },
	{ name: "Vivlos (Éclat d'été)", value: 109102, status: 'upcoming' },
	{ name: 'Vivlos (Voyage Étincelant)', value: 109101, status: 'upcoming' },
	{ name: 'Vodka (Unfreezable Firewater)', value: 100802, status: 'upcoming' },
	{ name: 'Vodka (Wild Top Gear)', value: 100801, status: 'released' },
	{ name: 'Win Variation (Dramatic Tutu)', value: 111701, status: 'upcoming' },
	{ name: 'Winning Ticket (Dream Deliverer)', value: 103502, status: 'upcoming' },
	{ name: 'Winning Ticket (Glorious Coat)', value: 103503, status: 'upcoming' },
	{ name: 'Winning Ticket (Get to Winning!)', value: 103501, status: 'released' },
	{ name: 'Wonder Acute (Butterfly Sting)', value: 110001, status: 'upcoming' },
	{ name: 'Yaeno Muteki (Attack of the Four White Meteors)', value: 107201, status: 'upcoming' },
	{ name: 'Yaeno Muteki (Black General, Zen)', value: 107202, status: 'upcoming' },
	{ name: 'Yamanin Zephyr (Fluttertail Spirit)', value: 107801, status: 'upcoming' },
	{ name: 'Yamanin Zephyr (Sugary Wind)', value: 107802, status: 'upcoming' },
	{ name: 'Yukino Bijin (Cute Sweet Flower of Mutsu)', value: 102901, status: 'upcoming' },
	{ name: 'Yukino Bijin (Snowy Girl of Tea and Cake)', value: 102902, status: 'upcoming' },
	{ name: 'Zenno Rob Roy (Heroic Author)', value: 104701, status: 'upcoming' },
	{ name: 'Zenno Rob Roy (Inlaid Stories)', value: 104702, status: 'upcoming' },
];

/** Data kartu support yang tersedia. */
export const supportCardOptions: SupportCard[] = [
	{ name: 'Admire Groove', value: 30265, rarity: 'SSR', type: 'Speed' },
	{ name: 'Admire Groove', value: 10133, rarity: 'R', type: 'Speed' },
	{ name: 'Admire Vega', value: 30162, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Admire Vega', value: 30077, rarity: 'SSR', type: 'Guts' },
	{ name: 'Admire Vega', value: 20041, rarity: 'SR', type: 'Power' },
	{ name: 'Admire Vega', value: 10075, rarity: 'R', type: 'Guts' },
	{ name: 'Agnes Digital', value: 30229, rarity: 'SSR', type: 'Wit' },
	{ name: 'Agnes Digital', value: 30085, rarity: 'SSR', type: 'Guts' },
	{ name: "Agnes Digital (Digital's Recharge Station)", value: 20005, rarity: 'SR', type: 'Guts' },
	{ name: 'Agnes Digital (Tracen Academy)', value: 10026, rarity: 'R', type: 'Power' },
	{ name: 'Agnes Tachyon', value: 30101, rarity: 'SSR', type: 'Speed' },
	{ name: 'Agnes Tachyon', value: 20059, rarity: 'SR', type: 'Guts' },
	{ name: 'Agnes Tachyon (Experimental Studies on Subject A)', value: 20012, rarity: 'SR', type: 'Wit' },
	{ name: 'Agnes Tachyon (Tracen Academy)', value: 10036, rarity: 'R', type: 'Wit' },
	{ name: 'Air Groove', value: 30159, rarity: 'SSR', type: 'Speed' },
	{ name: 'Air Groove', value: 30124, rarity: 'SSR', type: 'Wit' },
	{ name: 'Air Groove', value: 30106, rarity: 'SSR', type: 'Guts' },
	{ name: 'Air Groove (Nothing Escapes the Vice Prez)', value: 20004, rarity: 'SR', type: 'Guts' },
	{ name: 'Air Groove (Tracen Academy)', value: 10025, rarity: 'R', type: 'Guts' },
	{ name: 'Air Messiah', value: 30255, rarity: 'SSR', type: 'Wit' },
	{ name: 'Air Messiah', value: 10127, rarity: 'R', type: 'Wit' },
	{ name: 'Air Shakur', value: 30226, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Air Shakur', value: 30092, rarity: 'SSR', type: 'Speed' },
	{ name: 'Air Shakur', value: 20076, rarity: 'SR', type: 'Guts' },
	{ name: 'Air Shakur (7 More Centimeters)', value: 30013, rarity: 'SSR', type: 'Wit' },
	{ name: 'Air Shakur (Tracen Academy)', value: 10037, rarity: 'R', type: 'Wit' },
	{ name: 'Almond Eye', value: 30242, rarity: 'SSR', type: 'Speed' },
	{ name: 'Almond Eye', value: 10122, rarity: 'R', type: 'Speed' },
	{ name: 'Ancestors & Guides', value: 30137, rarity: 'SSR', type: 'Group' },
	{ name: 'Aoi Kiryuin (Tracen Academy)', value: 10022, rarity: 'R', type: 'Friend' },
	{ name: "Aoi Kiryuin (Trainer's Teamwork)", value: 20021, rarity: 'SR', type: 'Friend' },
	{ name: 'Aston Machan', value: 30149, rarity: 'SSR', type: 'Wit' },
	{ name: 'Aston Machan', value: 20055, rarity: 'SR', type: 'Speed' },
	{ name: 'Aston Machan', value: 10087, rarity: 'R', type: 'Speed' },
	{ name: 'Bamboo Memory', value: 30197, rarity: 'SSR', type: 'Guts' },
	{ name: 'Bamboo Memory', value: 30094, rarity: 'SSR', type: 'Power' },
	{ name: 'Bamboo Memory (Head-on Fight!)', value: 30042, rarity: 'SSR', type: 'Power' },
	{ name: 'Bamboo Memory (Tracen Academy)', value: 10065, rarity: 'R', type: 'Power' },
	{ name: 'Biko Pegasus', value: 30132, rarity: 'SSR', type: 'Guts' },
	{ name: 'Biko Pegasus', value: 20090, rarity: 'SR', type: 'Wit' },
	{ name: 'Biko Pegasus (Double Carrot Punch!)', value: 30020, rarity: 'SSR', type: 'Speed' },
	{ name: 'Biko Pegasus (Tracen Academy)', value: 10042, rarity: 'R', type: 'Speed' },
	{ name: 'Biwa Hayahide', value: 30113, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Biwa Hayahide', value: 30061, rarity: 'SSR', type: 'Wit' },
	{ name: 'Biwa Hayahide (Tracen Academy)', value: 10029, rarity: 'R', type: 'Power' },
	{ name: 'Biwa Hayahide (Trial Initiation)', value: 20006, rarity: 'SR', type: 'Power' },
	{ name: 'Blast Onepiece', value: 30232, rarity: 'SSR', type: 'Power' },
	{ name: 'Blast Onepiece', value: 10116, rarity: 'R', type: 'Power' },
	{ name: 'Bubble Gum Fellow', value: 20082, rarity: 'SR', type: 'Speed' },
	{ name: 'Bubble Gum Fellow', value: 10111, rarity: 'R', type: 'Speed' },
	{ name: 'Buena Vista', value: 30250, rarity: 'SSR', type: 'Guts' },
	{ name: 'Buena Vista', value: 30216, rarity: 'SSR', type: 'Power' },
	{ name: 'Buena Vista', value: 10118, rarity: 'R', type: 'Power' },
	{ name: 'Calstone Light O', value: 30267, rarity: 'SSR', type: 'Speed' },
	{ name: 'Calstone Light O', value: 10135, rarity: 'R', type: 'Speed' },
	{ name: 'Carvers of History', value: 30180, rarity: 'SSR', type: 'Group' },
	{ name: 'Cesario', value: 30217, rarity: 'SSR', type: 'Wit' },
	{ name: 'Cesario', value: 10115, rarity: 'R', type: 'Wit' },
	{ name: 'Cheval Grand', value: 30193, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Cheval Grand', value: 10105, rarity: 'R', type: 'Stamina' },
	{ name: 'Chrono Genesis', value: 30266, rarity: 'SSR', type: 'Wit' },
	{ name: 'Chrono Genesis', value: 10134, rarity: 'R', type: 'Wit' },
	{ name: 'Copano Rickey', value: 30211, rarity: 'SSR', type: 'Wit' },
	{ name: 'Copano Rickey', value: 20064, rarity: 'SR', type: 'Power' },
	{ name: 'Copano Rickey', value: 10092, rarity: 'R', type: 'Power' },
	{ name: "Curren Bouquetd'or", value: 20088, rarity: 'SR', type: 'Stamina' },
	{ name: "Curren Bouquetd'or", value: 10126, rarity: 'R', type: 'Stamina' },
	{ name: 'Curren Chan', value: 30237, rarity: 'SSR', type: 'Power' },
	{ name: 'Curren Chan', value: 30068, rarity: 'SSR', type: 'Wit' },
	{ name: 'Curren Chan', value: 20044, rarity: 'SR', type: 'Speed' },
	{ name: 'Curren Chan', value: 10073, rarity: 'R', type: 'Wit' },
	{ name: 'Daiichi Ruby', value: 30114, rarity: 'SSR', type: 'Guts' },
	{ name: 'Daiichi Ruby', value: 30270, rarity: 'SSR', type: 'Guts' },
	{ name: 'Daiichi Ruby', value: 10079, rarity: 'R', type: 'Guts' },
	{ name: 'Daitaku Helios', value: 30155, rarity: 'SSR', type: 'Wit' },
	{ name: 'Daitaku Helios', value: 30116, rarity: 'SSR', type: 'Speed' },
	{ name: 'Daitaku Helios', value: 30071, rarity: 'SSR', type: 'Guts' },
	{ name: "Daitaku Helios (Let's Get This Party Lit!)", value: 20024, rarity: 'SR', type: 'Power' },
	{ name: 'Daitaku Helios (Tracen Academy)', value: 10052, rarity: 'R', type: 'Power' },
	{ name: 'Daiwa Scarlet', value: 30227, rarity: 'SSR', type: 'Wit' },
	{ name: 'Daiwa Scarlet', value: 30148, rarity: 'SSR', type: 'Power' },
	{ name: 'Daiwa Scarlet', value: 30093, rarity: 'SSR', type: 'Guts' },
	{ name: 'Daiwa Scarlet', value: 30047, rarity: 'SSR', type: 'Guts' },
	{ name: "Daiwa Scarlet (Nothing Hard Work Can't Solve!)", value: 20002, rarity: 'SR', type: 'Wit' },
	{ name: 'Daiwa Scarlet (Tracen Academy)', value: 10023, rarity: 'R', type: 'Wit' },
	{ name: 'Dantsu Flame', value: 30269, rarity: 'SSR', type: 'Speed' },
	{ name: 'Dantsu Flame', value: 30209, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Dantsu Flame', value: 20077, rarity: 'SR', type: 'Wit' },
	{ name: 'Dantsu Flame', value: 10108, rarity: 'R', type: 'Wit' },
	{ name: 'Daring Heart', value: 30254, rarity: 'SSR', type: 'Wit' },
	{ name: 'Daring Heart', value: 20087, rarity: 'SR', type: 'Guts' },
	{ name: 'Daring Heart', value: 10121, rarity: 'R', type: 'Guts' },
	{ name: 'Daring Tact', value: 30248, rarity: 'SSR', type: 'Wit' },
	{ name: 'Daring Tact', value: 10120, rarity: 'R', type: 'Wit' },
	{ name: 'Dream Journey', value: 30246, rarity: 'SSR', type: 'Speed' },
	{ name: 'Dream Journey', value: 10119, rarity: 'R', type: 'Speed' },
	{ name: 'Duramente', value: 30262, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Duramente', value: 30190, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Duramente', value: 30178, rarity: 'SSR', type: 'Speed' },
	{ name: 'Duramente', value: 10101, rarity: 'R', type: 'Speed' },
	{ name: 'Durandal', value: 30268, rarity: 'SSR', type: 'Wit' },
	{ name: 'Durandal', value: 10136, rarity: 'R', type: 'Wit' },
	{ name: 'Eishin Flash', value: 30122, rarity: 'SSR', type: 'Speed' },
	{ name: 'Eishin Flash', value: 30172, rarity: 'SSR', type: 'Speed' },
	{ name: 'Eishin Flash (5:00 a.m.-Right on Schedule)', value: 20013, rarity: 'SR', type: 'Speed' },
	{ name: 'Eishin Flash (Tracen Academy)', value: 10038, rarity: 'R', type: 'Speed' },
	{ name: 'El Condor Pasa', value: 30161, rarity: 'SSR', type: 'Speed' },
	{ name: 'El Condor Pasa', value: 30102, rarity: 'SSR', type: 'Power' },
	{ name: 'El Condor Pasa', value: 20033, rarity: 'SR', type: 'Speed' },
	{ name: "El Condor Pasa (Champion's Passion)", value: 30007, rarity: 'SSR', type: 'Power' },
	{ name: 'El Condor Pasa (Tracen Academy)', value: 10011, rarity: 'R', type: 'Power' },
	{ name: 'Embodiment of Legends', value: 30241, rarity: 'SSR', type: 'Group' },
	{ name: 'Espoir City', value: 30251, rarity: 'SSR', type: 'Power' },
	{ name: 'Espoir City', value: 30222, rarity: 'SSR', type: 'Guts' },
	{ name: 'Espoir City', value: 10110, rarity: 'R', type: 'Guts' },
	{ name: 'Fine Motion', value: 30214, rarity: 'SSR', type: 'Power' },
	{ name: 'Fine Motion', value: 30167, rarity: 'SSR', type: 'Speed' },
	{ name: 'Fine Motion', value: 20037, rarity: 'SR', type: 'Guts' },
	{ name: 'Fine Motion (Tracen Academy)', value: 10028, rarity: 'R', type: 'Wit' },
	{ name: 'Fine Motion (Wave of Gratitude)', value: 30010, rarity: 'SSR', type: 'Wit' },
	{ name: 'Fuji Kiseki', value: 30219, rarity: 'SSR', type: 'Power' },
	{ name: 'Fuji Kiseki', value: 30271, rarity: 'SSR', type: 'Guts' },
	{ name: 'Fuji Kiseki (Tracen Academy)', value: 10049, rarity: 'R', type: 'Wit' },
	{ name: "Fuji Kiseki (Well, Look Who's Home)", value: 20001, rarity: 'SR', type: 'Wit' },
	{ name: 'Fusaichi Pandora', value: 30259, rarity: 'SSR', type: 'Speed' },
	{ name: 'Fusaichi Pandora', value: 10129, rarity: 'R', type: 'Speed' },
	{ name: 'Gentildonna', value: 30186, rarity: 'SSR', type: 'Speed' },
	{ name: 'Gentildonna', value: 10113, rarity: 'R', type: 'Speed' },
	{ name: 'Gold City', value: 30153, rarity: 'SSR', type: 'Power' },
	{ name: 'Gold City', value: 20049, rarity: 'SR', type: 'Wit' },
	{ name: 'Gold City (Run(my)way)', value: 30014, rarity: 'SSR', type: 'Speed' },
	{ name: 'Gold City (Tracen Academy)', value: 10017, rarity: 'R', type: 'Speed' },
	{ name: 'Gold Ship', value: 30168, rarity: 'SSR', type: 'Speed' },
	{ name: 'Gold Ship (That Tune I Became the Strongesr)', value: 30057, rarity: 'SSR', type: 'Speed' },
	{ name: 'Gold Ship', value: 20061, rarity: 'SR', type: 'Stamina' },
	{ name: 'Gold Ship (Breakaway Battleship)', value: 30004, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Gold Ship (Tracen Academy)', value: 10006, rarity: 'R', type: 'Stamina' },
	{ name: 'Gran Alegria', value: 30243, rarity: 'SSR', type: 'Guts' },
	{ name: 'Gran Alegria', value: 10124, rarity: 'R', type: 'Guts' },
	{ name: 'Grass Wonder', value: 30129, rarity: 'SSR', type: 'Guts' },
	{ name: 'Grass Wonder', value: 20065, rarity: 'SR', type: 'Guts' },
	{ name: 'Grass Wonder (Fairest Fleur)', value: 30006, rarity: 'SSR', type: 'Guts' },
	{ name: 'Grass Wonder (Tracen Academy)', value: 10009, rarity: 'R', type: 'Guts' },
	{ name: 'Haru Urara', value: 30171, rarity: 'SSR', type: 'Guts' },
	{ name: 'Haru Urara', value: 30098, rarity: 'SSR', type: 'Guts' },
	{ name: 'Haru Urara (Tracen Academy)', value: 10020, rarity: 'R', type: 'Guts' },
	{ name: "Haru Urara (Urara's Day Off!)", value: 30019, rarity: 'SSR', type: 'Guts' },
	{ name: 'Hishi Akebono', value: 30133, rarity: 'SSR', type: 'Wit' },
	{ name: 'Hishi Akebono', value: 20060, rarity: 'SR', type: 'Guts' },
	{ name: 'Hishi Akebono (Tracen Academy)', value: 10064, rarity: 'R', type: 'Guts' },
	{ name: 'Hishi Akebono (Who Wants the First Bite?)', value: 30040, rarity: 'SSR', type: 'Guts' },
	{ name: 'Hishi Amazon', value: 30223, rarity: 'SSR', type: 'Power' },
	{ name: 'Hishi Amazon', value: 30164, rarity: 'SSR', type: 'Guts' },
	{ name: 'Hishi Amazon (Reach to the Top!)', value: 20003, rarity: 'SR', type: 'Power' },
	{ name: 'Hishi Amazon (Tracen Academy)', value: 10024, rarity: 'R', type: 'Power' },
	{ name: 'Hishi Miracle', value: 30199, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Hishi Miracle', value: 10107, rarity: 'R', type: 'Stamina' },
	{ name: 'Hokko Tarumae', value: 30182, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Hokko Tarumae', value: 10090, rarity: 'R', type: 'Stamina' },
	{ name: 'Ikuno Dictus', value: 30238, rarity: 'SSR', type: 'Wit' },
	{ name: 'Ikuno Dictus', value: 30143, rarity: 'SSR', type: 'Guts' },
	{ name: 'Ikuno Dictus', value: 30099, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Ikuno Dictus', value: 30063, rarity: 'SSR', type: 'Power' },
	{ name: 'Ikuno Dictus (Never Skip Warm-Ups)', value: 20025, rarity: 'SR', type: 'Wit' },
	{ name: 'Ikuno Dictus (Tracen Academy)', value: 10053, rarity: 'R', type: 'Wit' },
	{ name: 'Inari One', value: 20032, rarity: 'SR', type: 'Guts' },
	{ name: 'Inari One', value: 10068, rarity: 'R', type: 'Guts' },
	{ name: 'Ines Fujin', value: 20030, rarity: 'SR', type: 'Wit' },
	{ name: 'Ines Fujin (Tracen Academy)', value: 10035, rarity: 'R', type: 'Guts' },
	{ name: 'Ines Fujin (Watch My Star Fly!)', value: 30011, rarity: 'SSR', type: 'Guts' },
	{ name: 'Jungle Pocket', value: 30240, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Jungle Pocket', value: 30203, rarity: 'SSR', type: 'Guts' },
	{ name: 'Jungle Pocket', value: 30158, rarity: 'SSR', type: 'Power' },
	{ name: 'Jungle Pocket', value: 30147, rarity: 'SSR', type: 'Speed' },
	{ name: 'Jungle Pocket', value: 20056, rarity: 'SR', type: 'Speed' },
	{ name: 'Jungle Pocket', value: 10089, rarity: 'R', type: 'Speed' },
	{ name: 'K.S. Miracle', value: 30195, rarity: 'SSR', type: 'Guts' },
	{ name: 'K.S. Miracle', value: 30130, rarity: 'SSR', type: 'Power' },
	{ name: 'K.S. Miracle', value: 20051, rarity: 'SR', type: 'Power' },
	{ name: 'K.S. Miracle', value: 10080, rarity: 'R', type: 'Power' },
	{ name: 'Katsuragi Ace', value: 30135, rarity: 'SSR', type: 'Speed' },
	{ name: 'Katsuragi Ace', value: 10091, rarity: 'R', type: 'Speed' },
	{ name: 'Kawakami Princess', value: 30096, rarity: 'SSR', type: 'Guts' },
	{ name: 'Kawakami Princess', value: 20089, rarity: 'SR', type: 'Power' },
	{ name: 'Kawakami Princess (Princess Bride)', value: 30039, rarity: 'SSR', type: 'Speed' },
	{ name: 'Kawakami Princess (Tracen Academy)', value: 10063, rarity: 'R', type: 'Speed' },
	{ name: 'King Halo (Tonight, We Waltz)', value: 30170, rarity: 'SSR', type: 'Power' },
	{ name: 'King Halo', value: 30056, rarity: 'SSR', type: 'Guts' },
	{ name: 'King Halo (First-Rate Plan)', value: 20020, rarity: 'SR', type: 'Speed' },
	{ name: 'King Halo (Tracen Academy)', value: 10048, rarity: 'R', type: 'Speed' },
	{ name: 'Kitasan Black', value: 30189, rarity: 'SSR', type: 'Power' },
	{ name: 'Kitasan Black', value: 20066, rarity: 'SR', type: 'Stamina' },
	{ name: 'Kitasan Black (Fire at My Heels)', value: 30028, rarity: 'SSR', type: 'Speed' },
	{ name: 'Kitasan Black (Tracen Academy)', value: 10055, rarity: 'R', type: 'Speed' },
	{ name: 'Light Hello', value: 30052, rarity: 'SSR', type: 'Friend' },
	{ name: 'Light Hello', value: 10083, rarity: 'R', type: 'Friend' },
	{ name: 'Lucky Lilac', value: 20084, rarity: 'SR', type: 'Wit' },
	{ name: 'Lucky Lilac', value: 10123, rarity: 'R', type: 'Wit' },
	{ name: 'Manhattan Cafe', value: 30157, rarity: 'SSR', type: 'Wit' },
	{ name: 'Manhattan Cafe', value: 30110, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Manhattan Cafe', value: 30075, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Manhattan Cafe (My Solo Drawn to Raindrop Drums)', value: 20008, rarity: 'SR', type: 'Stamina' },
	{ name: 'Manhattan Cafe (Tracen Academy)', value: 10031, rarity: 'R', type: 'Stamina' },
	{ name: 'Maruzensky', value: 30235, rarity: 'SSR', type: 'Speed' },
	{ name: 'Maruzensky', value: 30107, rarity: 'SSR', type: 'Speed' },
	{ name: 'Maruzensky', value: 20062, rarity: 'SR', type: 'Wit' },
	{ name: 'Maruzensky (Tracen Academy)', value: 10004, rarity: 'R', type: 'Speed' },
	{ name: 'Marvelous Sunday', value: 30131, rarity: 'SSR', type: 'Speed' },
	{ name: 'Marvelous Sunday', value: 30089, rarity: 'SSR', type: 'Power' },
	{ name: 'Marvelous Sunday', value: 30074, rarity: 'SSR', type: 'Guts' },
	{ name: 'Marvelous Sunday', value: 20079, rarity: 'SR', type: 'Power' },
	{ name: 'Marvelous Sunday (A Marvelous ☆ Plan)', value: 20015, rarity: 'SR', type: 'Wit' },
	{ name: 'Marvelous Sunday (Tracen Academy)', value: 10043, rarity: 'R', type: 'Wit' },
	{ name: 'Matikanefukukitaru', value: 30225, rarity: 'SSR', type: 'Power' },
	{ name: 'Matikanefukukitaru', value: 30078, rarity: 'SSR', type: 'Speed' },
	{ name: 'Matikanefukukitaru', value: 20078, rarity: 'SR', type: 'Speed' },
	{ name: "Matikanefukukitaru (Fate's Forecast)", value: 20016, rarity: 'SR', type: 'Wit' },
	{ name: 'Matikanefukukitaru (Tracen Academy)', value: 10044, rarity: 'R', type: 'Wit' },
	{ name: 'Matikanetannhauser', value: 30103, rarity: 'SSR', type: 'Wit' },
	{ name: 'Matikanetannhauser', value: 20069, rarity: 'SR', type: 'Speed' },
	{ name: 'Matikanetannhauser (Just Keep Going)', value: 30030, rarity: 'SSR', type: 'Guts' },
	{ name: 'Matikanetannhauser (Tracen Academy)', value: 10057, rarity: 'R', type: 'Guts' },
	{ name: 'Mayano Top Gun', value: 30151, rarity: 'SSR', type: 'Guts' },
	{ name: 'Mayano Top Gun', value: 30072, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mayano Top Gun (Cute + Cute = ?)', value: 20007, rarity: 'SR', type: 'Stamina' },
	{ name: 'Mayano Top Gun (Tracen Academy)', value: 10030, rarity: 'R', type: 'Stamina' },
	{ name: 'Mei Satake', value: 30160, rarity: 'SSR', type: 'Friend' },
	{ name: 'Mei Satake', value: 10094, rarity: 'R', type: 'Friend' },
	{ name: 'Meisho Doto', value: 30230, rarity: 'SSR', type: 'Speed' },
	{ name: 'Meisho Doto', value: 30079, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Meisho Doto (Fighting for Fortune)', value: 20017, rarity: 'SR', type: 'Guts' },
	{ name: 'Meisho Doto (Tracen Academy)', value: 10045, rarity: 'R', type: 'Guts' },
	{ name: 'Mejiro Ardan', value: 30234, rarity: 'SSR', type: 'Guts' },
	{ name: 'Mejiro Ardan', value: 30119, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mejiro Ardan', value: 20034, rarity: 'SR', type: 'Wit' },
	{ name: 'Mejiro Ardan', value: 10069, rarity: 'R', type: 'Wit' },
	{ name: 'Mejiro Bright', value: 30244, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro Bright', value: 30087, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro Bright', value: 10076, rarity: 'R', type: 'Stamina' },
	{ name: 'Mejiro Dober', value: 30174, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mejiro Dober', value: 20057, rarity: 'SR', type: 'Power' },
	{ name: 'Mejiro Dober (Ignore the Stares)', value: 20018, rarity: 'SR', type: 'Wit' },
	{ name: 'Mejiro Dober (My Thoughts, My Desires)', value: 30041, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mejiro Dober (Tracen Academy)', value: 10046, rarity: 'R', type: 'Wit' },
	{ name: 'Mejiro McQueen', value: 30260, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mejiro McQueen', value: 30172, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mejiro McQueen', value: 30139, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro McQueen', value: 20085, rarity: 'SR', type: 'Power' },
	{ name: 'Mejiro McQueen (Tracen Academy)', value: 10010, rarity: 'R', type: 'Stamina' },
	{ name: 'Mejiro McQueen (Your Team Ace)', value: 30022, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro Palmer', value: 30154, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mejiro Palmer', value: 30115, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro Palmer', value: 20036, rarity: 'SR', type: 'Stamina' },
	{ name: 'Mejiro Palmer (Go Ahead and Laugh)', value: 30027, rarity: 'SSR', type: 'Guts' },
	{ name: 'Mejiro Palmer (Tracen Academy)', value: 10054, rarity: 'R', type: 'Guts' },
	{ name: 'Mejiro Ramonu', value: 30175, rarity: 'SSR', type: 'Guts' },
	{ name: 'Mejiro Ramonu', value: 30134, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mejiro Ramonu', value: 20083, rarity: 'SR', type: 'Stamina' },
	{ name: 'Mejiro Ramonu', value: 10088, rarity: 'R', type: 'Wit' },
	{ name: 'Mejiro Ryan', value: 30258, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mejiro Ryan', value: 30176, rarity: 'SSR', type: 'Power' },
	{ name: 'Mejiro Ryan', value: 30048, rarity: 'SSR', type: 'Power' },
	{ name: 'Mejiro Ryan', value: 20040, rarity: 'SR', type: 'Stamina' },
	{ name: 'Mejiro Ryan (On and Off the Court)', value: 20010, rarity: 'SR', type: 'Power' },
	{ name: 'Mejiro Ryan (Tracen Academy)', value: 10033, rarity: 'R', type: 'Power' },
	{ name: 'Mihono Bourbon', value: 30141, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mihono Bourbon', value: 30121, rarity: 'SSR', type: 'Speed' },
	{ name: 'Mihono Bourbon', value: 30066, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mihono Bourbon (Fugue of Fortune)', value: 30059, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Mihono Bourbon (Pal-Assisted Training)', value: 20009, rarity: 'SR', type: 'Power' },
	{ name: 'Mihono Bourbon (Tracen Academy)', value: 10032, rarity: 'R', type: 'Power' },
	{ name: 'Mr. C.B.', value: 30097, rarity: 'SSR', type: 'Wit' },
	{ name: 'Mr. C.B.', value: 10078, rarity: 'R', type: 'Wit' },
	{ name: 'Nakayama Festa', value: 30163, rarity: 'SSR', type: 'Wit' },
	{ name: 'Nakayama Festa', value: 30108, rarity: 'SSR', type: 'Wit' },
	{ name: 'Nakayama Festa', value: 30043, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Nakayama Festa', value: 10067, rarity: 'R', type: 'Stamina' },
	{ name: 'Narita Brian', value: 30224, rarity: 'SSR', type: 'Speed' },
	{ name: 'Narita Brian', value: 30123, rarity: 'SSR', type: 'Guts' },
	{ name: 'Narita Brian', value: 30069, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Narita Brian', value: 30044, rarity: 'SSR', type: 'Speed' },
	{ name: 'Narita Brian', value: 10072, rarity: 'R', type: 'Speed' },
	{ name: 'Narita Taishin', value: 30201, rarity: 'SSR', type: 'Wit' },
	{ name: 'Narita Taishin', value: 30073, rarity: 'SSR', type: 'Wit' },
	{ name: 'Narita Taishin (Poolside High Tides)', value: 20014, rarity: 'SR', type: 'Speed' },
	{ name: 'Narita Taishin (Tracen Academy)', value: 10040, rarity: 'R', type: 'Speed' },
	{ name: 'Narita Top Road', value: 30086, rarity: 'SSR', type: 'Speed' },
	{ name: 'Narita Top Road', value: 20053, rarity: 'SR', type: 'Guts' },
	{ name: 'Narita Top Road', value: 10077, rarity: 'R', type: 'Speed' },
	{ name: 'Neo Universe', value: 30198, rarity: 'SSR', type: 'Wit' },
	{ name: 'Neo Universe', value: 10106, rarity: 'R', type: 'Wit' },
	{ name: 'Nice Nature', value: 30239, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Nice Nature', value: 30138, rarity: 'SSR', type: 'Guts' },
	{ name: 'Nice Nature', value: 30054, rarity: 'SSR', type: 'Wit' },
	{ name: 'Nice Nature', value: 20068, rarity: 'SR', type: 'Stamina' },
	{ name: "Nice Nature (It's Just Water)", value: 20019, rarity: 'SR', type: 'Guts' },
	{ name: 'Nice Nature (Messing Around)', value: 20026, rarity: 'SR', type: 'Wit' },
	{ name: 'Nice Nature (Tracen Academy)', value: 10047, rarity: 'R', type: 'Guts' },
	{ name: 'Nishino Flower', value: 30208, rarity: 'SSR', type: 'Guts' },
	{ name: 'Nishino Flower', value: 30082, rarity: 'SSR', type: 'Wit' },
	{ name: 'Nishino Flower (Even the Littlest Bud)', value: 30018, rarity: 'SSR', type: 'Speed' },
	{ name: 'Nishino Flower (Lifting Your Spirits)', value: 20027, rarity: 'SR', type: 'Power' },
	{ name: 'Nishino Flower (Tracen Academy)', value: 10041, rarity: 'R', type: 'Speed' },
	{ name: 'No Reason', value: 30200, rarity: 'SSR', type: 'Power' },
	{ name: 'No Reason', value: 10117, rarity: 'R', type: 'Power' },
	{ name: 'North Flight', value: 30185, rarity: 'SSR', type: 'Wit' },
	{ name: 'North Flight', value: 20081, rarity: 'SR', type: 'Guts' },
	{ name: 'North Flight', value: 10102, rarity: 'R', type: 'Wit' },
	{ name: 'Oguri Cap', value: 30146, rarity: 'SSR', type: 'Wit' },
	{ name: 'Oguri Cap', value: 20048, rarity: 'SR', type: 'Power' },
	{ name: 'Oguri Cap (Get Lots of Hugs for Me)', value: 30024, rarity: 'SSR', type: 'Power' },
	{ name: 'Oguri Cap (Tracen Academy)', value: 10005, rarity: 'R', type: 'Power' },
	{ name: 'Orfevre', value: 30187, rarity: 'SSR', type: 'Power' },
	{ name: 'Orfevre', value: 10103, rarity: 'R', type: 'Power' },
	{ name: 'Rhein Kraft', value: 30253, rarity: 'SSR', type: 'Speed' },
	{ name: 'Rhein Kraft', value: 30194, rarity: 'SSR', type: 'Power' },
	{ name: 'Rhein Kraft', value: 10114, rarity: 'R', type: 'Power' },
	{ name: 'Rice Shower', value: 30100, rarity: 'SSR', type: 'Wit' },
	{ name: 'Rice Shower', value: 30034, rarity: 'SSR', type: 'Guts' },
	{ name: 'Rice Shower', value: 20086, rarity: 'SR', type: 'Speed' },
	{ name: 'Rice Shower (Showered In Joy)', value: 30023, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Rice Shower (Tracen Academy)', value: 10015, rarity: 'R', type: 'Stamina' },
	{ name: 'Riko Kashimoto', value: 30036, rarity: 'SSR', type: 'Friend' },
	{ name: 'Riko Kashimoto', value: 10060, rarity: 'R', type: 'Friend' },
	{ name: 'Royce and Royce', value: 20071, rarity: 'SR', type: 'Guts' },
	{ name: 'Royce and Royce', value: 10100, rarity: 'R', type: 'Guts' },
	{ name: 'Ryoka Tsurugi', value: 30188, rarity: 'SSR', type: 'Friend' },
	{ name: 'Ryoka Tsurugi', value: 10104, rarity: 'R', type: 'Friend' },
	{ name: 'Sakura Bakushin O', value: 30184, rarity: 'SSR', type: 'Speed' },
	{ name: 'Sakura Bakushin O', value: 30083, rarity: 'SSR', type: 'Power' },
	{ name: 'Sakura Bakushin O', value: 20042, rarity: 'SR', type: 'Guts' },
	{ name: 'Sakura Bakushin O (Eat Fast! Yum Fast!)', value: 30015, rarity: 'SSR', type: 'Speed' },
	{ name: 'Sakura Bakushin O (Tracen Academy)', value: 10018, rarity: 'R', type: 'Speed' },
	{ name: 'Sakura Chiyono O', value: 30109, rarity: 'SSR', type: 'Power' },
	{ name: 'Sakura Chiyono O (Peak Sakura Season)', value: 30038, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Sakura Chiyono O (Tracen Academy)', value: 10062, rarity: 'R', type: 'Stamina' },
	{ name: 'Sakura Laurel', value: 30142, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Sakura Laurel', value: 30125, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Sakura Laurel', value: 20080, rarity: 'SR', type: 'Wit' },
	{ name: 'Sakura Laurel', value: 10085, rarity: 'R', type: 'Stamina' },
	{ name: 'Sasami Anshinzawa', value: 30080, rarity: 'SSR', type: 'Friend' },
	{ name: 'Sasami Anshinzawa', value: 10074, rarity: 'R', type: 'Friend' },
	{ name: 'Satono Diamond', value: 30221, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Satono Diamond', value: 30179, rarity: 'SSR', type: 'Wit' },
	{ name: 'Satono Diamond', value: 30088, rarity: 'SSR', type: 'Wit' },
	{ name: 'Satono Diamond (The Will to Overtake)', value: 30029, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Satono Diamond (Tracen Academy)', value: 10056, rarity: 'R', type: 'Stamina' },
	{ name: 'Seeking the Pearl', value: 30236, rarity: 'SSR', type: 'Speed' },
	{ name: 'Seeking the Pearl', value: 30095, rarity: 'SSR', type: 'Speed' },
	{ name: "Seeking the Pearl (The World's My Oyster)", value: 20029, rarity: 'SR', type: 'Guts' },
	{ name: 'Seeking the Pearl (Tracen Academy)', value: 10061, rarity: 'R', type: 'Guts' },
	{ name: 'Seiun Sky', value: 30204, rarity: 'SSR', type: 'Guts' },
	{ name: 'Seiun Sky (Paint the Sky Red)', value: 30055, rarity: 'SSR', type: 'Wit' },
	{ name: 'Seiun Sky', value: 20050, rarity: 'SR', type: 'Wit' },
	{ name: 'Seiun Sky (Foolproof Plan)', value: 30008, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Seiun Sky (Tracen Academy)', value: 10014, rarity: 'R', type: 'Stamina' },
	{ name: 'Shinko Windy', value: 30117, rarity: 'SSR', type: 'Power' },
	{ name: 'Shinko Windy (///WARNING GATE///)', value: 20031, rarity: 'SR', type: 'Speed' },
	{ name: 'Shinko Windy (Tracen Academy)', value: 10066, rarity: 'R', type: 'Speed' },
	{ name: 'Silence Suzuka', value: 30252, rarity: 'SSR', type: 'Power' },
	{ name: 'Silence Suzuka', value: 30076, rarity: 'SSR', type: 'Speed' },
	{ name: 'Silence Suzuka', value: 30062, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Silence Suzuka', value: 20063, rarity: 'SR', type: 'Speed' },
	{ name: 'Silence Suzuka (Beyond This Shining Moment)', value: 30002, rarity: 'SSR', type: 'Speed' },
	{ name: 'Silence Suzuka (Tracen Academy)', value: 10002, rarity: 'R', type: 'Speed' },
	{ name: 'Sirius Symboli', value: 30091, rarity: 'SSR', type: 'Wit' },
	{ name: 'Sirius Symboli', value: 20038, rarity: 'SR', type: 'Power' },
	{ name: 'Sirius Symboli', value: 10071, rarity: 'R', type: 'Power' },
	{ name: 'Smart Falcon', value: 30210, rarity: 'SSR', type: 'Speed' },
	{ name: 'Smart Falcon', value: 20045, rarity: 'SR', type: 'Power' },
	{ name: 'Smart Falcon (My Umadol Way! ☆)', value: 30017, rarity: 'SSR', type: 'Power' },
	{ name: 'Smart Falcon (Tracen Academy)', value: 10039, rarity: 'R', type: 'Power' },
	{ name: 'Sounds of Earth', value: 30191, rarity: 'SSR', type: 'Guts' },
	{ name: 'Sounds of Earth', value: 30173, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Sounds of Earth', value: 10098, rarity: 'R', type: 'Stamina' },
	{ name: 'Special Week', value: 30127, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Special Week', value: 30105, rarity: 'SSR', type: 'Power' },
	{ name: 'Special Week', value: 20043, rarity: 'SR', type: 'Guts' },
	{ name: 'Special Week (The Brightest Star in Japan!)', value: 30001, rarity: 'SSR', type: 'Guts' },
	{ name: 'Special Week (The Setting Sun And Rising Stars)', value: 30025, rarity: 'SSR', type: 'Speed' },
	{ name: 'Special Week (Tracen Academy)', value: 10001, rarity: 'R', type: 'Guts' },
	{ name: 'Stay Gold', value: 30264, rarity: 'SSR', type: 'Power' },
	{ name: 'Stay Gold', value: 10132, rarity: 'R', type: 'Power' },
	{ name: 'Still in Love', value: 30215, rarity: 'SSR', type: 'Speed' },
	{ name: 'Still in Love', value: 10096, rarity: 'R', type: 'Speed' },
	{ name: 'Super Creek (Piece of Mind)', value: 30016, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Super Creek (Tracen Academy)', value: 10019, rarity: 'R', type: 'Stamina' },
	{ name: 'Sweep Tosho', value: 30128, rarity: 'SSR', type: 'Wit' },
	{ name: 'Sweep Tosho', value: 30045, rarity: 'SSR', type: 'Speed' },
	{ name: 'Sweep Tosho', value: 20046, rarity: 'SR', type: 'Wit' },
	{ name: 'Sweep Tosho (Lamplit Training of a Witch-to-be)', value: 20023, rarity: 'SR', type: 'Speed' },
	{ name: 'Sweep Tosho (Tracen Academy)', value: 10050, rarity: 'R', type: 'Speed' },
	{ name: 'Symboli Kris S', value: 30247, rarity: 'SSR', type: 'Speed' },
	{ name: 'Symboli Kris S', value: 30228, rarity: 'SSR', type: 'Guts' },
	{ name: 'Symboli Kris S', value: 30220, rarity: 'SSR', type: 'Wit' },
	{ name: 'Symboli Kris S', value: 30136, rarity: 'SSR', type: 'Power' },
	{ name: 'Symboli Kris S', value: 30118, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Symboli Kris S', value: 10082, rarity: 'R', type: 'Stamina' },
	{ name: 'Symboli Rudolf', value: 30233, rarity: 'SSR', type: 'Wit' },
	{ name: 'Symboli Rudolf', value: 30037, rarity: 'SSR', type: 'Power' },
	{ name: 'Symboli Rudolf', value: 30090, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Symboli Rudolf', value: 20058, rarity: 'SR', type: 'Stamina' },
	{ name: 'Symboli Rudolf (Tracen Academy)', value: 10013, rarity: 'R', type: 'Wit' },
	{ name: 'T.M. Opera O', value: 30231, rarity: 'SSR', type: 'Guts' },
	{ name: 'T.M. Opera O', value: 30152, rarity: 'SSR', type: 'Wit' },
	{ name: 'T.M. Opera O', value: 20054, rarity: 'SR', type: 'Stamina' },
	{ name: 'T.M. Opera O (Tracen Academy)', value: 10012, rarity: 'R', type: 'Stamina' },
	{ name: 'Taiki Shuttle', value: 30218, rarity: 'SSR', type: 'Wit' },
	{ name: 'Taiki Shuttle', value: 30053, rarity: 'SSR', type: 'Speed' },
	{ name: 'Taiki Shuttle', value: 20067, rarity: 'SR', type: 'Wit' },
	{ name: 'Taiki Shuttle (Tracen Academy)', value: 10008, rarity: 'R', type: 'Speed' },
	{ name: 'Tamamo Cross', value: 30256, rarity: 'SSR', type: 'Guts' },
	{ name: 'Tamamo Cross', value: 30064, rarity: 'SSR', type: 'Guts' },
	{ name: 'Tamamo Cross', value: 20022, rarity: 'SR', type: 'Power' },
	{ name: 'Tamamo Cross (Split the Sky, White Lightning!)', value: 30009, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Tamamo Cross (Tracen Academy)', value: 10027, rarity: 'R', type: 'Stamina' },
	{ name: 'Tanino Gimlet', value: 30165, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Tanino Gimlet', value: 30145, rarity: 'SSR', type: 'Guts' },
	{ name: 'Tanino Gimlet', value: 20072, rarity: 'SR', type: 'Wit' },
	{ name: 'Tanino Gimlet', value: 10084, rarity: 'R', type: 'Guts' },
	{ name: 'Tap Dance City', value: 30166, rarity: 'SSR', type: 'Power' },
	{ name: 'Tap Dance City', value: 20075, rarity: 'SR', type: 'Power' },
	{ name: 'Tap Dance City', value: 10095, rarity: 'R', type: 'Power' },
	{ name: 'Tazuna Hayakawa (Tracen Academy)', value: 10021, rarity: 'R', type: 'Friend' },
	{ name: 'Tazuna Hayakawa (Tracen Reception)', value: 30021, rarity: 'SSR', type: 'Friend' },
	{ name: 'Team Sirius', value: 30081, rarity: 'SSR', type: 'Group' },
	{ name: "The Throne's Assemblage", value: 30067, rarity: 'SSR', type: 'Group' },
	{ name: 'Tokai Teio', value: 30213, rarity: 'SSR', type: 'Speed' },
	{ name: 'Tokai Teio', value: 30140, rarity: 'SSR', type: 'Speed' },
	{ name: 'Tokai Teio', value: 30111, rarity: 'SSR', type: 'Wit' },
	{ name: 'Tokai Teio', value: 20047, rarity: 'SR', type: 'Stamina' },
	{ name: 'Tokai Teio (Dream Big!)', value: 30003, rarity: 'SSR', type: 'Speed' },
	{ name: 'Tokai Teio (Regal Racers)', value: 30058, rarity: 'SSR', type: 'Power' },
	{ name: 'Tokai Teio (Tracen Academy)', value: 10003, rarity: 'R', type: 'Speed' },
	{ name: 'Tosen Jordan', value: 30084, rarity: 'SSR', type: 'Speed' },
	{ name: 'Tosen Jordan', value: 30273, rarity: 'SSR', type: 'Power' },
	{ name: 'Tosen Jordan', value: 20073, rarity: 'SR', type: 'Speed' },
	{ name: 'Tosen Jordan', value: 20035, rarity: 'SR', type: 'Stamina' },
	{ name: 'Tosen Jordan', value: 10070, rarity: 'R', type: 'Stamina' },
	{ name: 'Transcend', value: 30249, rarity: 'SSR', type: 'Power' },
	{ name: 'Transcend', value: 10125, rarity: 'R', type: 'Power' },
	{ name: 'Tsurumaru Tsuyoshi', value: 30169, rarity: 'SSR', type: 'Guts' },
	{ name: 'Tsurumaru Tsuyoshi', value: 20052, rarity: 'SR', type: 'Power' },
	{ name: 'Tsurumaru Tsuyoshi', value: 10081, rarity: 'R', type: 'Power' },
	{ name: 'Tucker Bryne', value: 30257, rarity: 'SSR', type: 'Friend' },
	{ name: 'Tucker Bryne', value: 10128, rarity: 'R', type: 'Friend' },
	{ name: 'Twin Turbo', value: 30181, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Twin Turbo', value: 30112, rarity: 'SSR', type: 'Power' },
	{ name: 'Twin Turbo', value: 30060, rarity: 'SSR', type: 'Power' },
	{ name: 'Twin Turbo (Tracen Academy)', value: 10051, rarity: 'R', type: 'Speed' },
	{ name: 'Twin Turbo (Turbo Booooost!)', value: 30026, rarity: 'SSR', type: 'Speed' },
	{ name: 'Verxina', value: 30205, rarity: 'SSR', type: 'Speed' },
	{ name: 'Verxina', value: 20070, rarity: 'SR', type: 'Power' },
	{ name: 'Verxina', value: 10097, rarity: 'R', type: 'Power' },
	{ name: 'Vivlos', value: 30263, rarity: 'SSR', type: 'Guts' },
	{ name: 'Vivlos', value: 30206, rarity: 'SSR', type: 'Speed' },
	{ name: 'Vivlos', value: 30192, rarity: 'SSR', type: 'Speed' },
	{ name: 'Vivlos', value: 30177, rarity: 'SSR', type: 'Power' },
	{ name: 'Vivlos', value: 10099, rarity: 'R', type: 'Power' },
	{ name: 'Vodka', value: 30245, rarity: 'SSR', type: 'Guts' },
	{ name: 'Vodka', value: 30202, rarity: 'SSR', type: 'Power' },
	{ name: 'Vodka', value: 30150, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Vodka', value: 20039, rarity: 'SR', type: 'Speed' },
	{ name: 'Vodka (Tracen Academy)', value: 10007, rarity: 'R', type: 'Power' },
	{ name: 'Vodka (Wild Rider)', value: 30005, rarity: 'SSR', type: 'Power' },
	{ name: 'Win Variation', value: 30261, rarity: 'SSR', type: 'Wit' },
	{ name: 'Win Variation', value: 10131, rarity: 'R', type: 'Wit' },
	{ name: 'Winning Ticket', value: 30183, rarity: 'SSR', type: 'Guts' },
	{ name: 'Winning Ticket', value: 30046, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Winning Ticket (BNWinner!)', value: 30012, rarity: 'SSR', type: 'Guts' },
	{ name: 'Winning Ticket (Dreams Do Come True!)', value: 30033, rarity: 'SSR', type: 'Power' },
	{ name: 'Winning Ticket (Tracen Academy)', value: 10016, rarity: 'R', type: 'Guts' },
	{ name: 'Wonder Acute', value: 30212, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Wonder Acute', value: 30156, rarity: 'SSR', type: 'Guts' },
	{ name: 'Wonder Acute', value: 10093, rarity: 'R', type: 'Guts' },
	{ name: 'Yaeno Muteki', value: 30120, rarity: 'SSR', type: 'Power' },
	{ name: 'Yaeno Muteki', value: 20074, rarity: 'SR', type: 'Stamina' },
	{ name: 'Yaeno Muteki (Fiery Discipline)', value: 30032, rarity: 'SSR', type: 'Power' },
	{ name: 'Yaeno Muteki (Tracen Academy)', value: 10058, rarity: 'R', type: 'Power' },
	{ name: 'Yamanin Zephyr', value: 30196, rarity: 'SSR', type: 'Speed' },
	{ name: 'Yamanin Zephyr', value: 30126, rarity: 'SSR', type: 'Power' },
	{ name: 'Yamanin Zephyr', value: 10086, rarity: 'R', type: 'Power' },
	{ name: 'Yayoi Akikawa', value: 30207, rarity: 'SSR', type: 'Friend' },
	{ name: 'Yayoi Akikawa', value: 10109, rarity: 'R', type: 'Friend' },
	{ name: 'Yukino Bijin', value: 30070, rarity: 'SSR', type: 'Power' },
	{ name: 'Yukino Bijin (City Girl 101)', value: 20011, rarity: 'SR', type: 'Guts' },
	{ name: 'Yukino Bijin (Hometown Cheers)', value: 30031, rarity: 'SSR', type: 'Wit' },
	{ name: 'Yukino Bijin (Tracen Academy)', value: 10034, rarity: 'R', type: 'Guts' },
	{ name: 'Zenno Rob Roy', value: 30104, rarity: 'SSR', type: 'Stamina' },
	{ name: 'Zenno Rob Roy', value: 30065, rarity: 'SSR', type: 'Speed' },
	{ name: 'Zenno Rob Roy (The Perfect Book for You)', value: 20028, rarity: 'SR', type: 'Stamina' },
	{ name: 'Zenno Rob Roy (Tracen Academy)', value: 10059, rarity: 'R', type: 'Stamina' },
];

/** Kumpulan blue sparks (stats) yang tersedia. */
export const blueSparkOptions: Option<number>[] = [
	{ name: 'Speed', value: 101 },
	{ name: 'Stamina', value: 201 },
	{ name: 'Power', value: 301 },
	{ name: 'Guts', value: 401 },
	{ name: 'Wit', value: 501 },
];

/** Kumpulan pink sparks (aptitude) yang tersedia. */
export const pinkSparkOptions: Option<number>[] = [
	{ name: 'Turf', value: 1101 },
	{ name: 'Dirt', value: 1201 },
	{ name: 'Front Runner', value: 2101 },
	{ name: 'Pace Chaser', value: 2201 },
	{ name: 'Late Surger', value: 2301 },
	{ name: 'End Closer', value: 2401 },
	{ name: 'Sprint', value: 3101 },
	{ name: 'Mile', value: 3201 },
	{ name: 'Medium', value: 3301 },
	{ name: 'Long', value: 3401 },
];

/** Kumpulan green sparks (unique skill) yang tersedia. */
export const greenSparkOptions: Option<number>[] = [
	{ name: 'Shooting Star', value: 10010101 },
	{ name: "Dazzl'n ♪ Diver", value: 10010201 },
	{ name: 'The View from the Lead Is Mine!', value: 10020101 },
	{ name: 'Sky-High Teio Step', value: 10030101 },
	{ name: 'Certain Victory', value: 10030201 },
	{ name: 'Red Shift/LP1211-M', value: 10040101 },
	{ name: 'A Kiss for Courage', value: 10040201 },
	{ name: 'Lights of Vaudeville', value: 10050101 },
	{ name: 'Triumphant Pulse', value: 10060101 },
	{ name: 'Anchors Aweigh!', value: 10070101 },
	{ name: 'Cut and Drive!', value: 10080101 },
	{ name: 'Resplendent Red Ace', value: 10090101 },
	{ name: 'Shooting for Victory!', value: 10100101 },
	{ name: "Where There's a Will, There's a Way", value: 10110101 },
	{ name: 'Superior Heal', value: 10110201 },
	{ name: 'You and Me! One-on-One!', value: 10120101 },
	{ name: 'The Duty of Dignity Calls', value: 10130101 },
	{ name: 'Legacy of the Strong', value: 10130201 },
	{ name: 'Victoria por plancha ☆', value: 10140101 },
	{ name: "Condor's Fury", value: 10140201 },
	{ name: 'This Dance Is for Vittoria!', value: 10150101 },
	{ name: 'Shadow Break', value: 10160101 },
	{ name: "Behold Thine Emperor's Divine Might", value: 10170101 },
	{ name: 'Blazing Pride', value: 10180101 },
	{ name: 'Eternal Moments', value: 10180201 },
	{ name: 'Angling and Scheming', value: 10200101 },
	{ name: '∴win Q.E.D.', value: 10230101 },
	{ name: 'Flashy☆Landing', value: 10240101 },
	{ name: 'Flowery☆Maneuver', value: 10240201 },
	{ name: 'G00 1st. F∞;', value: 10260101 },
	{ name: "Let's Pump Some Iron!", value: 10270101 },
	{ name: 'Blue Rose Closer', value: 10300101 },
	{ name: 'U=ma2', value: 10320101 },
	{ name: 'Our Ticket to Win!', value: 10350101 },
	{ name: 'Schwarzes Schwert', value: 10370101 },
	{ name: '#LookatCurren', value: 10380101 },
	{ name: 'KEEP IT REAL.', value: 10400101 },
	{ name: 'Genius x Bakushin = Victory', value: 10410101 },
	{ name: 'Pure Heart', value: 10450101 },
	{ name: 'SPARKLY☆STARDOM', value: 10460101 },
	{ name: 'Nemesis', value: 10500101 },
	{ name: 'Super-Duper Climax', value: 10520101 },
	{ name: 'I See Victory in My Future!', value: 10560101 },
	{ name: 'Bountiful Harvest', value: 10560201 },
	{ name: 'I Never Goof Up!', value: 10580101 },
	{ name: 'Just a Little Farther!', value: 10600101 },
	{ name: 'Prideful King', value: 10610101 },
];

/** Kumpulan white sparks (skill) yang tersedia. */
export const whiteSparkOptions: Option<number>[] = [
	{ name: 'February S.', value: 1000101 },
	{ name: 'Takamatsunomiya Kinen', value: 1000201 },
	{ name: 'Osaka Hai', value: 1000301 },
	{ name: 'Oka Sho', value: 1000401 },
	{ name: 'Satsuki Sho', value: 1000501 },
	{ name: 'Tenno Sho (Spring)', value: 1000601 },
	{ name: 'NHK Mile C.', value: 1000701 },
	{ name: 'Victoria Mile', value: 1000801 },
	{ name: 'Japanese Oaks', value: 1000901 },
	{ name: 'Japanese Derby', value: 1001001 },
	{ name: 'Yasuda Kinen', value: 1001101 },
	{ name: 'Takarazuka Kinen', value: 1001201 },
	{ name: 'Sprinters S.', value: 1001301 },
	{ name: 'Shuka Sho', value: 1001401 },
	{ name: 'Kikuka Sho', value: 1001501 },
	{ name: 'Tenno Sho (Autumn)', value: 1001601 },
	{ name: 'Queen Elizabeth II Cup', value: 1001701 },
	{ name: 'Mile Ch.', value: 1001801 },
	{ name: 'Japan C.', value: 1001901 },
	{ name: 'Champions C.', value: 1002001 },
	{ name: 'Hanshin J.F.', value: 1002101 },
	{ name: 'Asahi Hai F.S.', value: 1002201 },
	{ name: 'Arima Kinen', value: 1002301 },
	{ name: 'Hopeful S.', value: 1002401 },
	{ name: 'Teio Sho', value: 1002501 },
	{ name: 'J.D. Derby', value: 1002601 },
	{ name: 'JBC L. Classic', value: 1002701 },
	{ name: 'JBC Sprint', value: 1002801 },
	{ name: 'JBC Classic', value: 1002901 },
	{ name: 'Tokyo Daishoten', value: 1003001 },
	{ name: 'Right-Handed ○', value: 2000101 },
	{ name: 'Left-Handed ○', value: 2000201 },
	{ name: 'Tokyo Racecourse ○', value: 2000301 },
	{ name: 'Nakayama Racecourse ○', value: 2000401 },
	{ name: 'Hanshin Racecourse ○', value: 2000501 },
	{ name: 'Kyoto Racecourse ○', value: 2000601 },
	{ name: 'Chukyo Racecourse ○', value: 2000701 },
	{ name: 'Sapporo Racecourse ○', value: 2000801 },
	{ name: 'Hakodate Racecourse ○', value: 2000901 },
	{ name: 'Fukushima Racecourse ○', value: 2001001 },
	{ name: 'Niigata Racecourse ○', value: 2001101 },
	{ name: 'Kokura Racecourse ○', value: 2001201 },
	{ name: 'Standard Distance ○', value: 2001301 },
	{ name: 'Non-Standard Distance ○', value: 2001401 },
	{ name: 'Firm Conditions ○', value: 2001501 },
	{ name: 'Wet Conditions ○', value: 2001601 },
	{ name: 'Spring Runner ○', value: 2001701 },
	{ name: 'Summer Runner ○', value: 2001801 },
	{ name: 'Fall Runner ○', value: 2001901 },
	{ name: 'Winter Runner ○', value: 2002001 },
	{ name: 'Sunny Days ○', value: 2002101 },
	{ name: 'Cloudy Days ○', value: 2002201 },
	{ name: 'Rainy Days ○', value: 2002301 },
	{ name: 'Snowy Days ○', value: 2002401 },
	{ name: 'Inner Post Proficiency ○', value: 2002501 },
	{ name: 'Outer Post Proficiency ○', value: 2002601 },
	{ name: 'Maverick ○', value: 2002701 },
	{ name: 'Competitive Spirit ○', value: 2002801 },
	{ name: 'Target in Sight ○', value: 2002901 },
	{ name: 'Long Shot ○', value: 2003001 },
	{ name: 'Corner Adept ○', value: 2003301 },
	{ name: 'Corner Acceleration ○', value: 2003401 },
	{ name: 'Corner Recovery ○', value: 2003501 },
	{ name: 'Straightaway Adept', value: 2003601 },
	{ name: 'Straightaway Acceleration', value: 2003701 },
	{ name: 'Straightaway Recovery', value: 2003801 },
	{ name: 'Focus', value: 2004301 },
	{ name: 'Lay Low', value: 2004401 },
	{ name: 'Prudent Positioning', value: 2004501 },
	{ name: 'Ramp Up', value: 2004601 },
	{ name: 'Pace Strategy', value: 2004701 },
	{ name: 'Calm in a Crowd', value: 2004801 },
	{ name: 'Nimble Navigator', value: 2004901 },
	{ name: 'Go with the Flow', value: 2005001 },
	{ name: 'Homestretch Haste', value: 2005101 },
	{ name: 'Early Lead', value: 2005301 },
	{ name: 'Fast-Paced', value: 2005401 },
	{ name: 'Final Push', value: 2005501 },
	{ name: 'Stamina to Spare', value: 2005601 },
	{ name: 'Preferred Position', value: 2005701 },
	{ name: 'Prepared to Pass', value: 2005801 },
	{ name: 'Position Pilfer', value: 2005901 },
	{ name: 'Slick Surge', value: 2006001 },
	{ name: 'Outer Swell', value: 2006101 },
	{ name: 'Standing By', value: 2006201 },
	{ name: 'Masterful Gambit', value: 2006301 },
	{ name: 'Straightaway Spurt', value: 2006401 },
	{ name: 'Sprinting Gear', value: 2006501 },
	{ name: 'Wait-and-See', value: 2006601 },
	{ name: 'Gap Closer', value: 2006701 },
	{ name: 'Productive Plan', value: 2006801 },
	{ name: 'Watchful Eye', value: 2006901 },
	{ name: 'Updrafters', value: 2007001 },
	{ name: 'Rosy Outlook', value: 2007101 },
	{ name: 'Up-Tempo', value: 2007201 },
	{ name: 'Steadfast', value: 2007301 },
	{ name: 'Deep Breaths', value: 2007401 },
	{ name: 'Inside Scoop', value: 2007501 },
	{ name: 'Extra Tank', value: 2007601 },
	{ name: 'Trick (Front)', value: 2007701 },
	{ name: 'Trick (Rear)', value: 2007801 },
	{ name: 'Frenzied Front Runners', value: 2007901 },
	{ name: 'Frenzied Pace Chasers', value: 2008001 },
	{ name: 'Frenzied Late Surgers', value: 2008101 },
	{ name: 'Frenzied End Closers', value: 2008201 },
	{ name: 'Subdued Front Runners', value: 2008301 },
	{ name: 'Flustered Front Runners', value: 2008401 },
	{ name: 'Hesitant Front Runners', value: 2008501 },
	{ name: 'Subdued Pace Chasers', value: 2008601 },
	{ name: 'Flustered Pace Chasers', value: 2008701 },
	{ name: 'Hesitant Pace Chasers', value: 2008801 },
	{ name: 'Subdued Late Surgers', value: 2008901 },
	{ name: 'Flustered Late Surgers', value: 2009001 },
	{ name: 'Hesitant Late Surgers', value: 2009101 },
	{ name: 'Subdued End Closers', value: 2009201 },
	{ name: 'Flustered End Closers', value: 2009301 },
	{ name: 'Hesitant End Closers', value: 2009401 },
	{ name: 'Oi Racecourse ○', value: 2009501 },
	{ name: 'Sprint Straightaways ○', value: 2009601 },
	{ name: 'Sprint Corners ○', value: 2009701 },
	{ name: 'Huge Lead', value: 2009801 },
	{ name: 'Countermeasure', value: 2009901 },
	{ name: 'Metikulous Measures', value: 2010001 },
	{ name: 'Intimidate', value: 2010101 },
	{ name: 'Stop Right There!', value: 2010201 },
	{ name: 'Mile Straightaways ○', value: 2010301 },
	{ name: 'Mile Corners ○', value: 2010401 },
	{ name: 'Shifting Gears', value: 2010501 },
	{ name: 'Acceleration', value: 2010601 },
	{ name: 'Unyielding Spirit', value: 2010701 },
	{ name: 'Speed Eater', value: 2010801 },
	{ name: 'Opening Gambit', value: 2010901 },
	{ name: 'Medium Straightaways ○', value: 2011001 },
	{ name: 'Medium Corners ○', value: 2011101 },
	{ name: 'Hawkeye', value: 2011201 },
	{ name: 'Thunderbolt Stop', value: 2011301 },
	{ name: 'Soft Step', value: 2011401 },
	{ name: 'Tether', value: 2011501 },
	{ name: 'Murmur', value: 2011601 },
	{ name: 'Long Straightaways ○', value: 2011701 },
	{ name: 'Long Corners ○', value: 2011801 },
	{ name: 'Keeping the Lead', value: 2011901 },
	{ name: 'Passing Pro', value: 2012001 },
	{ name: 'Pressure', value: 2012101 },
	{ name: 'Stamina Eater', value: 2012201 },
	{ name: 'Smoke Screen', value: 2012301 },
	{ name: 'Front Runner Straightaways ○', value: 2012401 },
	{ name: 'Front Runner Corners ○', value: 2012501 },
	{ name: 'Dodging Danger', value: 2012601 },
	{ name: "Leader's Pride", value: 2012701 },
	{ name: 'Moxie', value: 2012801 },
	{ name: 'Second Wind', value: 2012901 },
	{ name: 'Restart', value: 2013001 },
	{ name: 'Pace Chaser Straightaways ○', value: 2013101 },
	{ name: 'Pace Chaser Corners ○', value: 2013201 },
	{ name: 'Shrewd Step', value: 2013301 },
	{ name: 'Straight Descent', value: 2013401 },
	{ name: 'Hydrate', value: 2013501 },
	{ name: 'Tactial Tweak', value: 2013601 },
	{ name: 'Disorient', value: 2013701 },
	{ name: 'Late Surger Straightaways ○', value: 2013801 },
	{ name: 'Late Surger Corners ○', value: 2013901 },
	{ name: 'Fighter', value: 2014001 },
	{ name: '1,500,000 CC', value: 2014101 },
	{ name: 'A Small Breather', value: 2014201 },
	{ name: 'Studious', value: 2014301 },
	{ name: 'Sharp Gaze', value: 2014401 },
	{ name: 'End Closer Straightaways ○', value: 2014501 },
	{ name: 'End Closer Corners ○', value: 2014601 },
	{ name: 'I Can See Right Through You', value: 2014701 },
	{ name: 'After-School Stroll', value: 2014801 },
	{ name: 'Levelheaded', value: 2014901 },
	{ name: 'Strategist', value: 2015001 },
	{ name: 'Intense Gaze', value: 2015101 },
	{ name: 'Front Runner Savvy ○', value: 2015201 },
	{ name: 'Pace Chaser Savvy ○', value: 2015301 },
	{ name: 'Late Surger Savvy ○', value: 2015401 },
	{ name: 'End Closer Savvy ○', value: 2015501 },
	{ name: 'Lucky Seven', value: 2015601 },
	{ name: 'Triple 7s', value: 2015701 },
	{ name: 'Highlander', value: 2015801 },
	{ name: 'Uma Stan', value: 2015901 },
	{ name: 'Groundwork', value: 2016001 },
	{ name: 'Tall Held High', value: 2016101 },
	{ name: 'Shake it Out', value: 2016201 },
	{ name: 'Sympathy', value: 2016301 },
	{ name: 'Lone Wolf', value: 2016401 },
	{ name: 'Slipstream', value: 2016501 },
	{ name: "Playtime's Over!", value: 2016601 },
	{ name: 'Top Pick', value: 2016701 },
	{ name: 'Ignited Spirit SPD', value: 2100101 },
	{ name: 'Ignited Spirit STA', value: 2100201 },
	{ name: 'Ignited Spirit PWR', value: 2100301 },
	{ name: 'Ignited Spirit GUTS', value: 2100401 },
	{ name: 'Ignited Spirit WIT', value: 2100501 },
	{ name: 'URA Finals', value: 3000101 },
	{ name: 'Unity Cup', value: 3000201 },
];
